### ISSUE TITLE
Simple Form to join SPy o.z.

### ISSUE THREAD

**Issue by Pytlicek** [pyconsk/spy.python.sk#2]
Simple Form to join SPy o.z.
If we have only static page, maybe google form will be enough.

**Comment by ricco386** [comment]
This is something we need to discuss internally first. Our Bylaw says that to become a  member you need a written recommendation from other member.

However I was thinking about having [several level of memberships](https://www.python.org/psf/membership/#what-membership-classes-are-there), since we do similar job than PSF (just localized for Slovakia), we can also have similar structure.

If there will be enough of us at the [meetup](https://www.meetup.com/pyconsk/events/242096084/) we can have a vote about additional membership types.

If we insipre be the PSF we can have following memberships:

1. Basic members
> Basic members are individuals or entities who are part of the Python language community and who have decided to declare their support for Python and agree to the community Code of Conduct.

2. Supporting members
> Supporting members make an annual donation to the SPy to sustain the Organization and support the Python community.

3. Managing members
> Managing members are people who dedicate at least five hours per month in one of the SPy's working groups - by helping organize, manage, conference, meetup or run infrastructure, etc.

PSF has 2 more but we are not so large organization so this should be enough. We can discuss in more details at meetup.

**Comment by jangondol** [comment]
As we discussed a couple of months ago after one of the meetups, let us first personally meet the person interested in joining. Let us see what they bring to the table and discuss membership with them face to face, the old fashioned way... :-)

For the record: if this issue is later read by someone who absolutely cannot travel to ANY one of our events, please reach out to us via e-mail and tell us more. We keep membership small (makes internal communication easier) but we have various opportunities to get involved.

Closing this issue because because it has been inactive for many months.
